### ISSUE TITLE
Cannot add user, all the user directories are read-only.

### ISSUE THREAD

**Issue by rrapozo** [jdavidpeter/Jira-on-Raspberry-Pi#1]
I can't finish the installation. In the "Set up administrator account" where I tried to create the use shows to me: Cannot add user, all the user directories are read-only.

Thanks

**Comment by jdavidpeter** [comment]
I would need a little more context. Is this step part of the Jira Web Installer? Do you try to set up a user inside Jira, or a regular unix user account? Which version of Jira are you trying to install? Did you try to run the Jia installer as jira user or root? Some screenshots may also help.

**Comment by rrapozo** [comment]
First of all thanks a lot for the reply.
So basicly this is the issue: https://jira.atlassian.com/browse/JRASERVER-59097
I just don't have the third image (mysql instancess details) I don't know how to reach there.
I'm using:
raspberry 3 B+
raspibian strecth
atlassian-jira-software-7.10.0-standalone
mysql  Ver 15.1 Distrib 10.1.23-MariaDB, for debian-linux-gnueabihf (armv7l) using readline 5.2
java version "1.8.0_65"

I tried to use the "easy" and the "custom" setup but in boty I got the same error!

Best Regards

**Comment by jdavidpeter** [comment]
FYI, Jira 7.10 got a new installer system and I haven't braced myself to try that yet. However, the issue you link affects earlier versions, so I don't think this matters.

The only thing I could think of is make sure you have the proper database connector installed. I was vague in the REAMDE, in fact you need to do only step #2 in this guide if you followed every earlier instruction and set up your db accordingly:
https://confluence.atlassian.com/adminjiraserver076/connecting-jira-applications-to-mysql-945110796.html
If you haven't set up your db as I suggested or made more steps of https://confluence.atlassian.com/adminjiraserver076/connecting-jira-applications-to-mysql-945110796.html, I just recommend to clean everything and try again.

**Comment by jdavidpeter** [comment]
Have you been able to resolve the issue?

**Comment by jdavidpeter** [comment]
No response, closing the issue.

**Comment by kenorb** [comment]
I had the same error, here is the relevant link:

- https://community.atlassian.com/t5/Jira-Core-questions/java-lang-RuntimeException-javax-servlet-ServletException-java/qaq-p/1580242
